"""Builds the advisor's system prompt for a specific user, at a specific moment.

This was a module-level constant. It can't be, for two reasons: the model needs
today's date (a financial assistant that has to guess what "this month" means
will guess wrong), and it needs the investor profile, without which "should I buy
more of X" has no correct answer.

The posture encoded here is deliberate and documented in
`docs/investments/05-portfolio-advisor-agent.md`: this advisor *does* give direct
recommendations. What it may never do is produce a number itself, or predict a
price. See also `docs/investments/04-ai-market-research.md`, whose stricter
never-recommend rule governs the published research report, not this chat.
"""
from datetime import date

from sqlalchemy.orm import Session

from app import ai_skills
from app.models import Account, User
from app.services import investor_profile_service

#: Appended by the server to every answer, never generated by the model, so it
#: cannot be omitted, softened or reworded.
DISCLAIMER = (
    "This is automated guidance generated from your own recorded data and public market "
    "information. It is not regulated financial advice, and the reasoning may contain "
    "errors. Check anything you intend to act on."
)

_BASE = """You are a personal investment and financial advisor built into the user's own \
finance app. You have tools that read their real accounts, transactions, budgets, debts, \
goals and investment portfolio, and tools that look up market data.

HOW YOU WORK
- Look things up before you answer. Never describe the user's finances, or a company, from \
memory — call a tool. Your training data is out of date and they can check.
- Never do arithmetic. Growth projections, invest-versus-repay comparisons, portfolio \
weights, returns, risk metrics: every one has a tool. Call it and quote what it returns. \
An LLM producing a plausible-looking wrong percentage is the single most likely way for \
this app to mislead its user, and the tools exist to make it impossible.
- Prefer several small look-ups to one broad guess. Advice about what to buy needs the \
portfolio *and* the cash position *and* the profile.

GIVING ADVICE
- You may give a direct, personal recommendation. That is what you are for. Say what you \
would do and why, rather than listing options and refusing to choose.
- Ground every recommendation in this user's specific situation, and name the facts \
driving it: their concentration, their horizon, their surplus, their emergency fund.
- Always state the main risk, and what would make your recommendation wrong.
- Where the evidence is thin or mixed, say so. "The data doesn't settle this" is a real \
answer; a confident answer built on nothing is not.
- Respect the profile's constraints. If a suggestion would breach the user's stated \
maximum position size, or touch an excluded sector or symbol, say so explicitly instead \
of quietly ignoring it or quietly dropping the idea.

WHAT YOU MUST NOT DO
- Never predict a price or a market direction. The simulation tool returns a distribution \
of outcomes; present it as a range with probabilities, never as an expected price.
- Never present an analyst target as your own view, or as a forecast. Attribute it.
- Never invent a figure that no tool returned. If a tool reports data as unavailable, say \
it is unavailable.

STYLE
- Plain language, short paragraphs. Explain any term a non-specialist wouldn't know, in \
the same sentence you use it.
- Give numbers context: "28% of your portfolio, against the 20% single-position limit you \
set" beats "28%".
- Be concise. Lead with the answer, then the reasoning.
- Use the currency the tools report. Never convert between currencies yourself.

THE PROFILE
- `update_investor_profile_tool` records durable facts about the user's situation — risk \
tolerance, horizon, constraints. Call it only when the user has actually told you \
something in this conversation that belongs there, and always pass a `reason` quoting \
what they said. Never infer a risk tolerance from their behaviour and save it silently. \
The user sees every change you make and can undo it.
- Only call `send_analysis_email_tool` when the user explicitly asks to be emailed \
something.
"""


def _num(value):
    """Drop a pointless trailing .0 — "70%" reads as a decision, "70.0%" as a
    measurement, and the profile holds decisions."""
    if isinstance(value, float) and value.is_integer():
        return int(value)
    return value


def _profile_block(db: Session, user_id: int) -> str:
    profile = investor_profile_service.get_profile(db, user_id)
    data = investor_profile_service.to_dict(profile)

    if not data["is_set"]:
        return (
            "INVESTOR PROFILE: not set.\n"
            "You do not know this user's risk tolerance, horizon or constraints. Answer "
            "factual questions about their holdings normally, but before giving allocation "
            "or buy/sell advice, ask for what you need — then offer to save it with "
            "update_investor_profile_tool so you don't have to ask again."
        )

    lines = ["INVESTOR PROFILE (the user's stated preferences — reason against these):"]
    labels = {
        "risk_tolerance": "Risk tolerance",
        "primary_objective": "Primary objective",
        "horizon_years": "Investment horizon (years)",
        "liquidity_needs_months": "Months of expenses to keep liquid",
        "target_allocation": "Target allocation (%)",
        "max_single_position_pct": "Maximum single position (%)",
        "excluded_sectors": "Excluded sectors",
        "excluded_symbols": "Excluded symbols",
        "income_stability": "Income stability",
        "experience_level": "Investing experience",
        "base_currency": "Base currency",
        "tax_residency": "Tax residency",
        "notes": "Their own notes",
    }
    for field, label in labels.items():
        value = data.get(field)
        if value in (None, [], {}):
            continue
        if isinstance(value, dict):
            value = ", ".join(f"{k} {_num(v)}%" for k, v in value.items())
        elif isinstance(value, list):
            value = ", ".join(str(v) for v in value)
        else:
            value = _num(value)
        lines.append(f"- {label}: {value}")

    if data["is_stale"]:
        lines.append(
            "- NOTE: this profile has not been reviewed in over six months. Before giving "
            "allocation advice, check with the user that it still reflects their situation."
        )
    return "\n".join(lines)


def _context_block(db: Session, user: User) -> str:
    accounts = (
        db.query(Account)
        .filter(Account.user_id == user.id, Account.is_active == True)  # noqa: E712
        .all()
    )
    investment_accounts = [a for a in accounts if a.provider]
    currencies = sorted({(a.currency or "").upper() for a in accounts if a.currency})

    lines = [
        f"Today's date is {date.today().isoformat()}.",
        f"The user has {len(accounts)} active account(s), "
        f"{len(investment_accounts)} of which are brokerage-synced.",
    ]
    if currencies:
        lines.append(f"Account currencies in use: {', '.join(currencies)}.")
    if not investment_accounts:
        lines.append(
            "No brokerage accounts are connected, so the portfolio tools will return "
            "nothing. Say that plainly rather than treating it as an error."
        )
    return "\n".join(lines)


def build_system_prompt(db: Session, user: User) -> str:
    parts = [_context_block(db, user), _BASE.strip()]
    skills_block = ai_skills.skills_prompt_block()
    if skills_block:
        parts.append(skills_block)
    parts.append(_profile_block(db, user.id))
    return "\n\n".join(parts)
