"""add_custom_type_to_debts_and_recurring_expense_tables

Revision ID: e7a884b96b62
Revises: 005
Create Date: 2026-05-05 18:21:33.269935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a884b96b62'
down_revision: Union[str, Sequence[str], None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'recurring_expenses' not in existing_tables:
        op.create_table('recurring_expenses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.Column('recurrence_interval', sa.Integer(), nullable=False),
        sa.Column('recurrence_unit', sa.String(length=20), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('next_due_date', sa.Date(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_recurring_expenses_id'), 'recurring_expenses', ['id'], unique=False)

    if 'recurring_expense_payments' not in existing_tables:
        op.create_table('recurring_expense_payments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recurring_expense_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('payment_date', sa.Date(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_recurring_expense_payments_id'), 'recurring_expense_payments', ['id'], unique=False)

    existing_columns = [c['name'] for c in inspector.get_columns('debts')]
    if 'custom_type' not in existing_columns:
        op.add_column('debts', sa.Column('custom_type', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    existing_columns = [c['name'] for c in inspector.get_columns('debts')]
    if 'custom_type' in existing_columns:
        op.drop_column('debts', 'custom_type')

    if 'recurring_expense_payments' in existing_tables:
        op.drop_index(op.f('ix_recurring_expense_payments_id'), table_name='recurring_expense_payments')
        op.drop_table('recurring_expense_payments')

    if 'recurring_expenses' in existing_tables:
        op.drop_index(op.f('ix_recurring_expenses_id'), table_name='recurring_expenses')
        op.drop_table('recurring_expenses')
    # ### end Alembic commands ###
