#!/usr/bin/env python3
"""Generate VAPID keys and append them to the repo-root .env file.

Usage (from repo root):
    uv run python scripts/generate_vapid_keys.py

Restart the backend after running so it picks up the new keys.
"""
from __future__ import annotations

import base64
from pathlib import Path

from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import ec


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def generate_vapid_keypair() -> tuple[str, str]:
    private_key = ec.generate_private_key(ec.SECP256R1(), default_backend())
    priv_int = private_key.private_numbers().private_value
    priv_bytes = priv_int.to_bytes(32, byteorder="big")
    pub_numbers = private_key.public_key().public_numbers()
    pub_bytes = (
        b"\x04"
        + pub_numbers.x.to_bytes(32, byteorder="big")
        + pub_numbers.y.to_bytes(32, byteorder="big")
    )
    return _b64url(pub_bytes), _b64url(priv_bytes)


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    env_path = repo_root / ".env"

    public_key, private_key = generate_vapid_keypair()
    lines = [
        "",
        "# Web Push VAPID keys (generated by scripts/generate_vapid_keys.py)",
        f"VAPID_PUBLIC_KEY={public_key}",
        f"VAPID_PRIVATE_KEY={private_key}",
        "VAPID_SUBJECT=mailto:admin@example.com",
        "",
    ]

    if env_path.exists():
        content = env_path.read_text(encoding="utf-8")
        if "VAPID_PUBLIC_KEY=" in content:
            print("VAPID_PUBLIC_KEY already exists in .env — remove old keys first or edit manually.")
            return
        env_path.write_text(content.rstrip() + "\n" + "\n".join(lines), encoding="utf-8")
    else:
        example = repo_root / ".env.example"
        base = example.read_text(encoding="utf-8") if example.exists() else ""
        env_path.write_text(base.rstrip() + "\n" + "\n".join(lines), encoding="utf-8")

    print(f"Wrote VAPID keys to {env_path}")
    print("Restart the backend, then use Enable desktop notifications on the Notifications page.")


if __name__ == "__main__":
    main()
